<?php
/* Add our new field to the content types and/or comments */
function comment_addl_form_alter(&$form, $form_state, $form_id) { // form override
  if ($form_id == 'forum_node_form') { // add field to forum content type
    unset($form['taxonomy']['5']['#options'][4]);
    $form['upoints'] = array(
    '#type' => 'textfield',
    '#title' => t('Points'),
    '#maxlength' => 10,
    '#size' => 5,
    '#id' => t('edit-field-upoints-0-value'),
    '#default_value' => $node->upoints,
    );
  }
  if ($form_id == 'comment_form') { // add field to comment content type
    $form['upoints'] = array(
    '#type' => 'textfield',
    '#title' => t('Points'),
    '#maxlength' => 10,
    '#size' => 5,
    '#id' => t('edit-field-upoints-0-value'),
    '#default_value' => $comment->upoints,
    );
  }
}

/* set up permissions */
function comment_addl_perm() {
  return array('view upoints field');
}

/* operations for handling the values inserted into a node's form */
function comment_addl_nodeapi(&$node, $op) {
  $node_link = l(t('view'), 'node/' . $node->nid);
  $watchdog_args = array(
    '@type' => $node->type,
    '%title' => $node->title,
  );
  //watchdog('comment_addl', '@type: updated %title.', $watchdog_args, WATCHDOG_NOTICE, $node_link);
  switch ($op) {
    case 'insert': // insert in the database
      watchdog('comment_addl', 'INSERT', null, WATCHDOG_NOTICE, $node_link);
      db_query("INSERT INTO {comment_addl} (xid, type, upoints) VALUES(%d, '%s', '%s')", $node->nid, 'node', $node->upoints);
      break;
    case 'update': // update database entry
      $result = db_fetch_object(db_query("SELECT upoints FROM {comment_addl} WHERE type='node' AND xid = %d", $node->nid));
      if ($result->upoints) {
        watchdog('comment_addl', 'UPDATE', null, WATCHDOG_NOTICE, $node_link);
        db_query("UPDATE {comment_addl} SET upoints = %d WHERE xid = %d AND type = '%s'", $node->upoints, $node->nid, 'node');
      } else {
        watchdog('comment_addl', 'UPDATE-INSERT', null, WATCHDOG_NOTICE, $node_link);
        db_query("INSERT INTO {comment_addl} (xid, type, upoints) VALUES(%d, '%s', '%s')", $node->nid, 'node', $node->upoints);
      }
      break;
    case 'view': // get it from the database for display
      watchdog('comment_addl', 'VIEW', null, WATCHDOG_NOTICE, $node_link);
      if (user_access('view upoints field')) {
        $result = db_fetch_object(db_query("SELECT upoints FROM {comment_addl} WHERE type='node' AND xid = %d", $node->nid));
        if ($result->upoints) {
          $node->upoints = $result->upoints;
        }
      }
      break;
  }
}

/* operations for handling the values inserted into a comment's form */
function comment_addl_comment(&$comment, $op) {
  switch ($op) {
    case 'insert': // insert in the database
      db_query("INSERT INTO {comment_addl} (xid, type, upoints) VALUES(%d, '%s', '%s')", $comment['cid'], 'comment', $comment['upoints']);
      break;
    case 'update': // update database entry
      db_query("UPDATE {comment_addl} SET upoints = '%s' WHERE xid = %d AND type = '%s')", $comment->upoints, $comment->cid, 'comment');
      break;
    case 'view': // get it from the database for display
      if (user_access('view upoints field')) {
        $result = db_fetch_object(db_query("SELECT upoints FROM {comment_addl} WHERE type='comment' AND xid = %d", $comment->cid));
        $comment->upoints = $result->upoints;
      }
      break;
  }
}
